### ISSUE TITLE
Results wrong? 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_generalized_dipole#4]
I just executed the example notebook and I get the following results: 
![Unknown](https://user-images.githubusercontent.com/3854739/91705351-1a208680-eb7d-11ea-8307-131d50cc33ea.png)

**Comment by ashtonmv** [comment]
That looks correct. I edited the fields to be unequal on either side of the slab, since symmetric fields were already possible in DFT using Alavi + Sanchez' method. With inequivalent fields the dipole correction is also more clearly visible.

**Comment by jan-janssen** [comment]
Ok, sorry I was not reading the details - just executed the notebook. Maybe it is reasonable to update the default notebook as other user might be confused as well.
